import { Prompt, Model, StyleOption, ColorSwatch } from './types';

export const MODELS: Model[] = ['FluxArt', 'VideoGen', 'GPT Image', 'Midjourney'];

export const CATEGORIES = [
  'Abstract', 'Cyberpunk', 'Fantasy', 'Nature', 'Portrait', 'Surreal', 
  'Sci-Fi', 'Minimal', 'Vaporwave', 'Architectural', 'Macro', 'Concept Art'
];

export const TAGS = [
  'cinematic', 'ethereal', 'neon', 'dreamlike', 'hyperreal', 'moody', 
  'vibrant', 'dark', 'pastel', 'futuristic', 'organic', 'dramatic', 
  'serene', 'chaotic', 'symmetrical', 'atmospheric'
];

export const STYLE_OPTIONS: StyleOption[] = [
  { id: 's1', label: 'Photoreal', emoji: '📷', modifier: 'photorealistic, 8k, ultra detailed' },
  { id: 's2', label: 'Cinematic', emoji: '🎥', modifier: 'cinematic lighting, film still, anamorphic' },
  { id: 's3', label: 'Anime', emoji: '🎌', modifier: 'anime style, detailed illustration, vibrant' },
  { id: 's4', label: 'Oil Paint', emoji: '🖼️', modifier: 'oil painting, thick impasto, classical' },
  { id: 's5', label: 'Cyberpunk', emoji: '🌃', modifier: 'cyberpunk, neon reflections, rainy night' },
  { id: 's6', label: 'Surreal', emoji: '🌀', modifier: 'surrealism, melting forms, dream logic' },
  { id: 's7', label: 'Minimal', emoji: '⚪', modifier: 'minimalist, clean composition, negative space' },
  { id: 's8', label: 'Vaporwave', emoji: '🌸', modifier: 'vaporwave, retro 80s, pastel grid, chrome' },
];

export const COLOR_SWATCHES: ColorSwatch[] = [
  { id: 'c1', label: 'Midnight', value: '#0f172a', descriptor: 'deep midnight blues and indigos' },
  { id: 'c2', label: 'Neon Violet', value: '#7c3aed', descriptor: 'electric violet and magenta glows' },
  { id: 'c3', label: 'Aurora', value: '#14b8a6', descriptor: 'aurora teal and emerald gradients' },
  { id: 'c4', label: 'Ember', value: '#f97316', descriptor: 'fiery orange and burnt sienna tones' },
  { id: 'c5', label: 'Rose Quartz', value: '#f472b6', descriptor: 'soft rose and dusty pink hues' },
  { id: 'c6', label: 'Obsidian', value: '#1f2937', descriptor: 'obsidian black with silver highlights' },
  { id: 'c7', label: 'Solar', value: '#eab308', descriptor: 'golden hour and warm sunlight' },
  { id: 'c8', label: 'Arctic', value: '#bae6fd', descriptor: 'arctic ice and pale cyan' },
  { id: 'c9', label: 'Lush', value: '#166534', descriptor: 'lush forest greens and moss' },
  { id: 'c10', label: 'Candy', value: '#c026ff', descriptor: 'candy pop pinks and purples' },
];

const PICSUM_SEEDS = [
  1011, 1005, 1027, 1033, 1040, 106, 160, 201, 251, 29, 30, 31, 40, 41, 42, 43, 44, 48, 50, 60, 64, 65, 77, 82, 88, 90, 96, 100, 133, 160, 180, 201, 222, 251, 29
];

function getImageUrl(seed: number, w = 600, h = 800) {
  return `https://picsum.photos/id/${seed}/${w}/${h}`;
}

export const MOCK_PROMPTS: Prompt[] = [
  {
    id: 'p1',
    imageUrl: getImageUrl(1011, 600, 780),
    prompt: 'Majestic snow-capped mountain peaks piercing through layers of golden clouds at sunrise',
    fullPrompt: 'Majestic snow-capped mountain peaks piercing through layers of golden clouds at sunrise, dramatic volumetric lighting, crisp alpine air, ultra realistic landscape photography, 8k',
    creator: 'Aether',
    creatorAvatar: 'https://picsum.photos/id/1005/64/64',
    likes: 12480,
    views: 89200,
    model: 'Midjourney',
    tags: ['cinematic', 'atmospheric', 'dramatic'],
    category: 'Nature',
    createdAt: '2025-05-19T14:22:00Z',
  },
  {
    id: 'p2',
    imageUrl: getImageUrl(1005, 600, 620),
    prompt: 'Close-up portrait of a young woman with wet hair and soft morning light on her face, freckles visible',
    fullPrompt: 'Close-up portrait of a young woman with wet hair and soft morning light on her face, natural freckles, subtle emotion, shallow depth of field, photoreal skin texture, 8k',
    creator: 'NeonFable',
    creatorAvatar: 'https://picsum.photos/id/201/64/64',
    likes: 9870,
    views: 74300,
    model: 'FluxArt',
    tags: ['hyperreal', 'serene', 'organic'],
    category: 'Portrait',
    createdAt: '2025-05-20T09:41:00Z',
  },
  {
    id: 'p3',
    imageUrl: getImageUrl(1027, 600, 850),
    prompt: 'Crystal clear turquoise water with ripples and light rays penetrating deep into the ocean',
    fullPrompt: 'Crystal clear turquoise water with gentle ripples, dramatic sunlight rays penetrating deep into the ocean, underwater photography, ultra sharp, serene and immersive',
    creator: 'Lumina',
    creatorAvatar: 'https://picsum.photos/id/1009/64/64',
    likes: 15620,
    views: 104500,
    model: 'GPT Image',
    tags: ['serene', 'atmospheric', 'organic'],
    category: 'Nature',
    createdAt: '2025-05-18T22:05:00Z',
  },
  {
    id: 'p4',
    imageUrl: getImageUrl(1033, 600, 660),
    prompt: 'Minimal wooden cabin surrounded by tall pine trees and soft morning fog in the mountains',
    fullPrompt: 'Minimal wooden cabin surrounded by tall pine trees and thick soft morning fog in the mountains, moody atmosphere, natural color grading, peaceful solitude, landscape photography',
    creator: 'ConcreteGhost',
    creatorAvatar: 'https://picsum.photos/id/160/64/64',
    likes: 7430,
    views: 52100,
    model: 'FluxArt',
    tags: ['atmospheric', 'serene', 'minimal'],
    category: 'Architectural',
    createdAt: '2025-05-20T18:33:00Z',
  },
  {
    id: 'p5',
    imageUrl: getImageUrl(1040, 600, 920),
    prompt: 'Vast golden wheat field at sunset with dramatic pink and orange sky and low rolling hills',
    fullPrompt: 'Vast golden wheat field at sunset with dramatic pink and orange sky, low rolling hills in the distance, warm cinematic lighting, peaceful rural landscape, 8k',
    creator: 'WillowWisp',
    creatorAvatar: 'https://picsum.photos/id/29/64/64',
    likes: 11290,
    views: 68300,
    model: 'Midjourney',
    tags: ['cinematic', 'warm', 'organic'],
    category: 'Nature',
    createdAt: '2025-05-17T11:12:00Z',
  },
  {
    id: 'p6',
    imageUrl: getImageUrl(201, 600, 580),
    prompt: 'Retro pink vintage car parked on an empty road with palm trees and a bright blue sky',
    fullPrompt: 'Retro pink vintage car parked on an empty road with tall palm trees and a bright blue sky, California summer vibes, clean composition, vibrant colors, film photography',
    creator: 'GlitchWave',
    creatorAvatar: 'https://picsum.photos/id/251/64/64',
    likes: 6890,
    views: 41200,
    model: 'VideoGen',
    tags: ['vibrant', 'minimal', 'warm'],
    category: 'Vaporwave',
    createdAt: '2025-05-21T03:55:00Z',
  },
  {
    id: 'p7',
    imageUrl: getImageUrl(160, 600, 740),
    prompt: 'Extreme macro of a single pink rose petal covered in tiny water droplets, soft bokeh background',
    fullPrompt: 'Extreme macro of a single pink rose petal covered in tiny water droplets, incredibly sharp detail, soft pink bokeh background, delicate and beautiful, professional macro photography',
    creator: 'MacroMoss',
    creatorAvatar: 'https://picsum.photos/id/30/64/64',
    likes: 5340,
    views: 29800,
    model: 'GPT Image',
    tags: ['macro', 'organic', 'serene'],
    category: 'Macro',
    createdAt: '2025-05-19T07:28:00Z',
  },
  {
    id: 'p8',
    imageUrl: getImageUrl(42, 600, 810),
    prompt: 'Majestic white wolf standing on a snowy mountain ridge with aurora borealis in the night sky',
    fullPrompt: 'Majestic white wolf standing on a snowy mountain ridge with vibrant green aurora borealis in the night sky, wind blowing through thick fur, epic wildlife photography, cinematic',
    creator: 'FrostByte',
    creatorAvatar: 'https://picsum.photos/id/40/64/64',
    likes: 13980,
    views: 95100,
    model: 'FluxArt',
    tags: ['dramatic', 'cinematic', 'atmospheric'],
    category: 'Nature',
    createdAt: '2025-05-18T16:49:00Z',
  },
  {
    id: 'p9',
    imageUrl: getImageUrl(44, 600, 650),
    prompt: 'Elegant woman with dark hair in a flowing black dress standing in an empty minimalist white room',
    fullPrompt: 'Elegant woman with dark hair in a flowing black dress standing in an empty minimalist white room, dramatic side lighting, high fashion editorial photography, clean and sophisticated',
    creator: 'SynthSoul',
    creatorAvatar: 'https://picsum.photos/id/64/64/64',
    likes: 8720,
    views: 60400,
    model: 'Midjourney',
    tags: ['minimal', 'dramatic', 'moody'],
    category: 'Portrait',
    createdAt: '2025-05-20T12:14:00Z',
  },
  {
    id: 'p10',
    imageUrl: getImageUrl(48, 600, 880),
    prompt: 'Ancient moss-covered stone ruins in a dense green jungle with shafts of sunlight breaking through the canopy',
    fullPrompt: 'Ancient moss-covered stone ruins in a dense green jungle with dramatic shafts of sunlight breaking through the canopy, atmospheric, mysterious, National Geographic style',
    creator: 'Archivox',
    creatorAvatar: 'https://picsum.photos/id/60/64/64',
    likes: 10540,
    views: 71900,
    model: 'FluxArt',
    tags: ['atmospheric', 'organic', 'dramatic'],
    category: 'Concept Art',
    createdAt: '2025-05-16T20:37:00Z',
  },
  {
    id: 'p11',
    imageUrl: getImageUrl(60, 600, 600),
    prompt: 'Young girl with long flowing hair standing in a field of tall golden grass during golden hour',
    fullPrompt: 'Young girl with long flowing hair standing in a field of tall golden grass during golden hour, warm backlighting, dreamy atmosphere, soft focus, cinematic portrait',
    creator: 'Stellaris',
    creatorAvatar: 'https://picsum.photos/id/65/64/64',
    likes: 14730,
    views: 88300,
    model: 'GPT Image',
    tags: ['dreamlike', 'warm', 'organic'],
    category: 'Portrait',
    createdAt: '2025-05-21T01:03:00Z',
  },
  {
    id: 'p12',
    imageUrl: getImageUrl(82, 600, 760),
    prompt: 'Narrow wet Tokyo street at night with glowing red lanterns and reflections on the pavement',
    fullPrompt: 'Narrow wet Tokyo street at night with glowing red paper lanterns, neon signs, and beautiful reflections on the wet pavement, moody cinematic color grading, Blade Runner atmosphere',
    creator: 'Kurai',
    creatorAvatar: 'https://picsum.photos/id/100/64/64',
    likes: 9230,
    views: 66700,
    model: 'VideoGen',
    tags: ['neon', 'cinematic', 'moody'],
    category: 'Cyberpunk',
    createdAt: '2025-05-19T23:41:00Z',
  },
  {
    id: 'p13',
    imageUrl: getImageUrl(90, 600, 700),
    prompt: 'Surreal minimalist landscape of rolling sand dunes under a pastel pink and purple sky',
    fullPrompt: 'Surreal minimalist landscape of rolling sand dunes under a pastel pink and purple sky, soft shadows, delicate color palette, dreamlike and peaceful, fine art photography',
    creator: 'DuneWander',
    creatorAvatar: 'https://picsum.photos/id/133/64/64',
    likes: 7840,
    views: 44900,
    model: 'Midjourney',
    tags: ['surreal', 'minimal', 'serene'],
    category: 'Surreal',
    createdAt: '2025-05-17T15:20:00Z',
  },
  {
    id: 'p14',
    imageUrl: getImageUrl(180, 600, 830),
    prompt: 'Sleek modern black sports car parked in an empty brutalist concrete parking garage at night',
    fullPrompt: 'Sleek modern black sports car parked in an empty brutalist concrete parking garage at night, dramatic single light source, reflections on wet floor, moody and cinematic',
    creator: 'PureForm',
    creatorAvatar: 'https://picsum.photos/id/201/64/64',
    likes: 6120,
    views: 33800,
    model: 'FluxArt',
    tags: ['minimal', 'moody', 'dramatic'],
    category: 'Minimal',
    createdAt: '2025-05-20T08:55:00Z',
  },
  {
    id: 'p15',
    imageUrl: getImageUrl(222, 600, 610),
    prompt: 'Tiny wooden boat floating on a perfectly still lake surrounded by dense pine forest at sunrise',
    fullPrompt: 'Tiny wooden boat floating on a perfectly still lake surrounded by dense pine forest at sunrise, mirror-like water reflections, peaceful and serene, warm morning light, landscape photography',
    creator: 'Worldseed',
    creatorAvatar: 'https://picsum.photos/id/251/64/64',
    likes: 16890,
    views: 124300,
    model: 'Midjourney',
    tags: ['serene', 'atmospheric', 'organic'],
    category: 'Nature',
    createdAt: '2025-05-15T10:18:00Z',
  },
  {
    id: 'p16',
    imageUrl: getImageUrl(29, 600, 870),
    prompt: 'Old wise man with deep wrinkles and kind eyes sitting on a wooden bench in warm sunlight',
    fullPrompt: 'Old wise man with deep wrinkles and kind eyes sitting on a wooden bench in warm sunlight, incredible skin texture and character, emotional portrait, photoreal, 8k',
    creator: 'QuietFrame',
    creatorAvatar: 'https://picsum.photos/id/30/64/64',
    likes: 9740,
    views: 54100,
    model: 'GPT Image',
    tags: ['hyperreal', 'warm', 'cinematic'],
    category: 'Portrait',
    createdAt: '2025-05-18T04:29:00Z',
  },
  {
    id: 'p17',
    imageUrl: getImageUrl(31, 600, 640),
    prompt: 'Modern glass house built into a rocky cliff overlooking the ocean at dusk',
    fullPrompt: 'Modern glass house built into a rocky cliff overlooking the ocean at dusk, warm interior lights glowing, dramatic sky, architectural photography, peaceful and luxurious',
    creator: 'Icebound',
    creatorAvatar: 'https://picsum.photos/id/40/64/64',
    likes: 5560,
    views: 31200,
    model: 'FluxArt',
    tags: ['architectural', 'atmospheric', 'cinematic'],
    category: 'Architectural',
    createdAt: '2025-05-21T06:07:00Z',
  },
  {
    id: 'p18',
    imageUrl: getImageUrl(50, 600, 790),
    prompt: 'Stunning woman with glowing skin and flowing dark hair against a deep black background, studio lighting',
    fullPrompt: 'Stunning woman with glowing skin and flowing dark hair against a deep black background, perfect studio lighting, high fashion beauty portrait, elegant and powerful, 8k',
    creator: 'VoidQueen',
    creatorAvatar: 'https://picsum.photos/id/64/64/64',
    likes: 19230,
    views: 138900,
    model: 'Midjourney',
    tags: ['dramatic', 'hyperreal', 'minimal'],
    category: 'Portrait',
    createdAt: '2025-05-16T13:44:00Z',
  },
  {
    id: 'p19',
    imageUrl: getImageUrl(77, 600, 680),
    prompt: 'Abstract flowing black and white marble texture with soft dramatic lighting',
    fullPrompt: 'Abstract flowing black and white marble texture with soft dramatic lighting, elegant organic shapes, fine art photography, minimalist and sophisticated',
    creator: 'Molten',
    creatorAvatar: 'https://picsum.photos/id/88/64/64',
    likes: 4310,
    views: 26400,
    model: 'VideoGen',
    tags: ['minimal', 'abstract', 'moody'],
    category: 'Abstract',
    createdAt: '2025-05-19T19:11:00Z',
  },
  {
    id: 'p20',
    imageUrl: getImageUrl(96, 600, 720),
    prompt: 'Cozy wooden cabin with warm glowing windows in a snowy forest at night',
    fullPrompt: 'Cozy wooden cabin with warm glowing windows in a snowy forest at night, gentle snow falling, inviting and peaceful atmosphere, cinematic winter photography',
    creator: 'Horizon',
    creatorAvatar: 'https://picsum.photos/id/100/64/64',
    likes: 12140,
    views: 78200,
    model: 'FluxArt',
    tags: ['serene', 'warm', 'atmospheric'],
    category: 'Nature',
    createdAt: '2025-05-20T05:36:00Z',
  },
  {
    id: 'p21',
    imageUrl: getImageUrl(160, 600, 550),
    prompt: 'Beautiful macro of a butterfly with intricate wing patterns resting on a green leaf',
    fullPrompt: 'Beautiful macro of a butterfly with intricate colorful wing patterns resting on a green leaf, extreme sharpness, soft natural lighting, stunning detail, professional macro',
    creator: 'PetalLab',
    creatorAvatar: 'https://picsum.photos/id/133/64/64',
    likes: 3940,
    views: 21900,
    model: 'GPT Image',
    tags: ['macro', 'organic', 'vibrant'],
    category: 'Macro',
    createdAt: '2025-05-18T09:52:00Z',
  },
  {
    id: 'p22',
    imageUrl: getImageUrl(251, 600, 910),
    prompt: 'Ancient stone temple ruins overgrown with vines and jungle foliage at golden hour',
    fullPrompt: 'Ancient stone temple ruins overgrown with vines and jungle foliage at golden hour, dramatic light rays through trees, mysterious and beautiful, epic scale, cinematic',
    creator: 'TitanForge',
    creatorAvatar: 'https://picsum.photos/id/180/64/64',
    likes: 13850,
    views: 96700,
    model: 'Midjourney',
    tags: ['dramatic', 'organic', 'cinematic'],
    category: 'Concept Art',
    createdAt: '2025-05-17T22:18:00Z',
  },
];

// Helper to get a random image URL for generated prompts
export function getRandomImageUrl(): string {
  const seed = PICSUM_SEEDS[Math.floor(Math.random() * PICSUM_SEEDS.length)];
  const h = 620 + Math.floor(Math.random() * 320);
  return getImageUrl(seed, 600, h);
}

// Fake translations (Spanish) for the translate toggle in modal
export const FAKE_TRANSLATIONS: Record<string, string> = {
  p1: 'Un samurái solitario de pie en una isla flotante sobre las nubes al atardecer, pétalos de cerezo arremolinándose en el viento.',
  p2: 'Mercado callejero cyberpunk hiperdetallado de noche, letreros de neón resbaladizos por la lluvia, peces koi holográficos nadando en el aire.',
  p3: 'Mujer etérea hecha de mercurio líquido y luz estelar, flotando en un vasto vacío de obsidiana, reflejos de galaxias distantes.',
  p6: 'Atardecer vaporwave sobre una autopista de cuadrícula infinita, pirámides cromadas a lo lejos, palmeras retro-futuristas.',
  p8: 'Un majestuoso lobo blanco con ojos cyan brillantes de pie en un acantilado nevado bajo las auroras boreales.',
  p15: 'Vista aérea épica de un árbol antiguo colosal cuyo dosel forma un continente flotante entero con ríos y aldeas.',
  p18: 'Una mujer increíblemente hermosa con cabello hecho de llama viva y galaxias en sus iris, reina cósmica.',
};

export function getTranslation(promptId: string): string {
  return FAKE_TRANSLATIONS[promptId] || 'Traducción no disponible para este prompt.';
}

 


